name: Go Web App CI/CD

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: 334yash
  APP_NAME: go-web-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Go app
      run: |
        go mod download
        go build -o main .
        echo "✅ Go app built successfully"

    - name: Test
      run: |
        go test ./...
        echo "✅ Tests passed"

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest .
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
        echo "✅ Docker image pushed to DockerHub"

    - name: Update deployment file
      run: |
        # Just for confirmation
        echo "📦 Docker image ready for deployment"
        echo "Image: ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest"

  success-message:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
    - name: Completion message
      run: |
        echo "🎉 CI/CD Pipeline Completed Successfully!"
        echo "✅ Code built and tested"
        echo "✅ Docker image pushed to DockerHub"
        echo "📝 Next: Setup Kubernetes deployment"

